#! /bin/sh

#source "$XDG_CONFIG_HOME/colors.sh"

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d 1 2 3 4 5 6 7 8 9 10

### BSPWM configuration ###
bspc config border_width         2
bspc config window_gap          12
bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_by_distance	 true
bspc config focus_follows_pointer true

bspc rule -a Gimp desktop='^8' state=floating follow=on
#bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

### BPSWM coloring ###
bspc config normal_border_color		"#7f7f7f"
bspc config focused_border_color 	"#81A1C1"
bspc config presel_feedback_color	"#81A1C1"

### Autostart ###

# fix mouse pointer size problem
xsetroot -xcf /usr/share/icons/breeze_cursors/cursors/left_ptr 24

# fix font qt dpi problem
xrandr --dpi 96

# Increase key speed via a rate change
xset r rate 300 50

# Run polkit agent for requesting permissions
polkit-dumb-agent &

# Compositor
picom &

# Wallpaper
feh --bg-fill --randomize ~/Pictures/Wallpapers/* #wallpaper

# Polybar
$HOME/.config/polybar/./launch.sh
